version: '3'

services:

  db:
    image: postgres:11-alpine
    restart: always
    expose:
      - "5432"
    ports:
      - ${POSTGRES_DEV_PORT}:5432
    environment:
      POSTGRES_DB: node-api
      POSTGRES_USER: nodeadmin
      POSTGRES_PASSWORD: nodepass
  
  
  db-test:
    image: postgres:11-alpine
    restart: always
    expose:
      - "5432"
    ports:
      - ${POSTGRES_TEST_PORT}:5432
    environment:
      POSTGRES_DB: node-api-test
      POSTGRES_USER: nodeadmin
      POSTGRES_PASSWORD: nodepass

  adminer:
    image: adminer:latest
    restart: always
    ports:
      - "8080:8080"
    environment:
      ADMINER_DEFAULT_SERVER: database
      ADMINER_DESIGN: lucas-sandery